### PR TITLE
Curseforge new layout update

### PR DESCRIPTION
**Pull request by alarofrunetotem**
Hi, discovered a couple of bug in my patch.
Submitting fixes here

### CODE REVIEW

**Comment by alarofrunetotem** [comment]
Added also quick fixes for new curse layout (also automatically translates addon urls to new host).

**Comment by alarofrunetotem** [comment]
Fix for new www.curseforge.com site should be now complete

**Comment by alar77** [comment]
Reorganized my accounts on github, so my old comments ended under "ghost"

**Comment by ephraim** [comment]
Thank you for your work.

**Comment by alar77** [comment]
You are welcome :)

**Comment by jwhipp** [comment]
I just tested on from master today,  still seeing this:

**Pull request merged**
