### PR TITLE
Addon partof package

### PR DESCRIPTION
**Pull request by samako93**
Here we go this time... hopefully.

I noticed with some addons (Auctioneer specifically) that come with several modules, that the URL generated for updates was incorrect, since it was based off of the addon's title in the .toc file.

For this addon, the .toc has an extra tag called X-Part-Of with the name of the correct full addon.

Listing all of these single modules under one name allows the URL to be generated correctly, and updates all of the single modules since they are packaged together with it.

I've just added a small section that notifies the user that the addon is a bundle, and allows the addon to be updated.

### CODE REVIEW

**Comment by nicdumz** [comment]
Could you perhaps clean your git history? A PR containing a revert is a bit strange ;-)

**Comment by ephraim** [comment]
Please update your patches to latest lcurse and please provide a PullRequest without a revert in it.

**Comment by samako93** [comment]
I thought I did a reset, but turns out I did a revert. All fixed up though. Cheers

**Comment by ephraim** [comment]
couldn't apply directly as there were merge conflicts.
Anyway applied. Thanks.

**Pull request closed without merging**
